=== baloise/dashboard-plus/src/main/resources/com/baloise/confluence/dashboardplus/jira/config/JiraEvalSpec.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	targetNamespace="http://www.baloise.com/confluence/dashboardplus/jira/config"
	xmlns:tns="http://www.baloise.com/confluence/dashboardplus/jira/config"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="jiraEvalSpec">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="defaultProjectSpec">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="issueTypeSpec" maxOccurs="unbounded"
								minOccurs="1" type="tns:issueTypeSpecType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="specificProjectSpec" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="issueTypeSpec" maxOccurs="unbounded"
								minOccurs="1" type="tns:issueTypeSpecType" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="projectKey" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="issueTypeSpecType">
		<xs:sequence>
			<xs:element type="xs:string" name="fieldId" />
			<xs:element type="xs:string" name="fieldValueAssociatedWithSucceeded"
				maxOccurs="unbounded" minOccurs="1" />
			<xs:element type="xs:string" name="fieldValueAssociatedWithFailed"
				maxOccurs="unbounded" minOccurs="1" />
			<xs:element type="xs:string" name="fieldValueAssociatedWithSkipped"
				maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="issueTypeName" use="required" />
	</xs:complexType>
</xs:schema>

=== baloise/dashboard-plus/src/main/resources/com/baloise/confluence/dashboardplus/jira/config/JiraEvalSpec_Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:jiraEvalSpec
	xmlns:tns="http://www.baloise.com/confluence/dashboardplus/jira/config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.baloise.com/confluence/dashboardplus/jira/config JiraEvalSpec.xsd ">
	<tns:defaultProjectSpec>
		<tns:issueTypeSpec issueTypeName="Requirement">
			<tns:fieldId>cf[11150]</tns:fieldId>
			<tns:fieldValueAssociatedWithSucceeded>Done</tns:fieldValueAssociatedWithSucceeded>
			<tns:fieldValueAssociatedWithFailed>Failed</tns:fieldValueAssociatedWithFailed>
			<tns:fieldValueAssociatedWithSkipped>Wont be done</tns:fieldValueAssociatedWithSkipped>
			<tns:fieldValueAssociatedWithSkipped>In Progress</tns:fieldValueAssociatedWithSkipped>
		</tns:issueTypeSpec>
		<tns:issueTypeSpec issueTypeName="Sub Testcase">
			<tns:fieldId>cf[12850]</tns:fieldId>
			<tns:fieldValueAssociatedWithSucceeded>OK</tns:fieldValueAssociatedWithSucceeded>
			<tns:fieldValueAssociatedWithFailed>NOK</tns:fieldValueAssociatedWithFailed>
			<tns:fieldValueAssociatedWithSkipped>SKIPPED</tns:fieldValueAssociatedWithSkipped>
		</tns:issueTypeSpec>
		<tns:issueTypeSpec issueTypeName="Test">
			<tns:fieldId>cf[11152]</tns:fieldId>
			<tns:fieldValueAssociatedWithSucceeded>PASSED</tns:fieldValueAssociatedWithSucceeded>
			<tns:fieldValueAssociatedWithFailed>ERROR</tns:fieldValueAssociatedWithFailed>
			<tns:fieldValueAssociatedWithSkipped>SKIPPED</tns:fieldValueAssociatedWithSkipped>
		</tns:issueTypeSpec>
	</tns:defaultProjectSpec>
	<tns:specificProjectSpec projectKey="GALRE">
		<tns:issueTypeSpec issueTypeName="Test">
			<tns:fieldId>cf[11152]</tns:fieldId>
			<tns:fieldValueAssociatedWithSucceeded>PASSED</tns:fieldValueAssociatedWithSucceeded>
			<tns:fieldValueAssociatedWithSucceeded>OK</tns:fieldValueAssociatedWithSucceeded>
			<tns:fieldValueAssociatedWithFailed>ERROR</tns:fieldValueAssociatedWithFailed>
			<tns:fieldValueAssociatedWithSkipped>SKIPPED</tns:fieldValueAssociatedWithSkipped>
		</tns:issueTypeSpec>
	</tns:specificProjectSpec>
</tns:jiraEvalSpec>
